common:
  name: classifier
  mode: debug
  template_dir: views
  model: model_12G3c
  datastore_path: '/home/sergey-msu/Work/pit/classifier'
models:
  model_12G3c:
    file_path: 'models/trained/model_12G3c_v0_1.pt'
    device: 'gpu'
