server:
  name: classifier
  host: 127.0.0.1
  port: 1909
  debug: False
  model: model_12G3c
  datastore_path: '/home/sergey-msu/Work/pit/classifier'
models:
  model_12G3c:
    file_path: 'models/trained/model_12G3c_v0_1.pt'
    device: 'cpu'
    threshold: 0.7